### ISSUE TITLE
can you give me some paper or references of UVa/Padova simulitor

### ISSUE THREAD

**Issue by OneBirding** [jxx123/simglucose#16]
can you give me some paper or references of UVa/Padova simulitor,I can learn a lot params and formula

of your code

**Comment by sumanabasu** [comment]
The link to UVA Padova 2013 paper is in the README:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4454102/
or
https://journals.sagepub.com/doi/pdf/10.1177/1932296813514502

This paper (UVA Padova 2013) includes the Glucagon pathway as well, but simglucose is based on the 2008 version, which only has the insulin pathway. However, you'll find everything you might want to know about the 2008 version in the 2013 paper. Hope this helps!

**Comment by jxx123** [comment]
Thanks @sumanabasu for the paper pointers. Will close this issue.
