### ISSUE TITLE
Query: How is the upper bound of the action space determined?

### ISSUE THREAD

**Issue by sumanabasu** [jxx123/simglucose#21]
The environment action space is bounded between (0, 30). While 0 makes sense as it can be interpreted as 'no insulin has been administered', I'm wondering how the upper limit 30 is determined? Also, what is the unit?

**Comment by jxx123** [comment]
It is the upper limit of the insulin pump for basal. See here https://github.com/jxx123/simglucose/blob/master/simglucose/params/pump_params.csv, the gym environment uses Insulet pump by default.

The unit is U/min (1 U = 1/6000 pmol/L).
