### ISSUE TITLE
How can I customize patients？

### ISSUE THREAD

**Issue by Lvwenzhou** [jxx123/simglucose#22]
I have the basal physiological information of the real patients. Can I customize patients? And what parameters may I lack?

**Comment by jxx123** [comment]
If you want to customize patient parameters, you need to change this parameter csv file https://github.com/jxx123/simglucose/blob/master/simglucose/params/vpatient_params.csv. 

For basal, u2ss in the csv file is the one you need to change, its unit is pmol/(kg * min). 
For more details on those parameters and the patient model, please take a look at the appendix of this pape rhttps://pubmed.ncbi.nlm.nih.gov/17926672/. 

The patient model is defined here in the code: https://github.com/jxx123/simglucose/blob/master/simglucose/patient/t1dpatient.py#L117
