### ISSUE TITLE
About CR and CF values in Quest.csv

### ISSUE THREAD

**Issue by aacelik** [jxx123/simglucose#24]
Hi, 

When I compute CR and CF values manually, they do not match with the values given in Quest.csv. I computed them as follows. I know body weight (BW in vpatient_params.csv) and total daily insulin (TDI in Quest.csv) so CR=5.7*BW/TDI and CF=1960/TDI. How did you calculate CR and CF values in Quest.csv?

Thanks.

**Comment by jxx123** [comment]
These parameters come from 2008 UVa/Padova Simulator academic version in Matlab.
