### ISSUE TITLE
How did you obtain the parameters in vpatient_params.csv?

### ISSUE THREAD

**Issue by aacelik** [jxx123/simglucose#26]
Hi,

Where did you get the in-silico patient parameters in vpatient_params.csv? I have checked the internet and UVa-Padova S2008, S2013, S2018 papers but could not see the sources of their synthetic patient parameters. Can you please share your source or explain how you generate the parameters?

Thanks.

**Comment by jxx123** [comment]
Sorry for the late reply. I used the parameters in 2008 UVa/Padova Simulator academic version (in Matlab).

**Comment by aacelik** [comment]
How can I access the academic version of the simulator (i.e. MATLAB code and patient parameter files)? If you have the link or the files, could you share them?

**Comment by jxx123** [comment]
You should be able to request a copy here https://tegvirginia.com/software/t1dms/.

**Comment by aacelik** [comment]
Thanks
