### ISSUE TITLE
Are there currently any differences in the simulator between basal and bolus

### ISSUE THREAD

**Issue by eseglo** [jxx123/simglucose#28]
Hi, 
I would like to understand if there is any difference between applying in the action basal or bolus insulin. From my understanding, basal should be long-acting and bolus rapid acting. But,  [here](https://github.com/jxx123/simglucose/blob/8f6696a628543a553fd9d5aa55d935be23bd7b38/simglucose/simulation/env.py#L53) both of them are added, after conversion from the pump, and then passed to the model and solver. So they do not seem to have different effects, am I right? Can I use any of them in my controller.
Thanks a lot.

**Comment by jxx123** [comment]
Yes, there is no difference between basal and bolus. Feel free to use any of them.

**Comment by eseglo** [comment]
Thanks
