### ISSUE TITLE
Add 5min, 10 min etc delta of BG as an observation

### ISSUE THREAD

**Issue by harispoljo** [jxx123/simglucose#5]
Add delta of BG to the observation when using gym.

**Comment by jxx123** [comment]
Hi harispolijo,

Thanks for your comment. Can you give me more details on why you need the delta BG in the observation? I believe the delta BG values can be computed inside of the controller policy. You should be able to cache the historical BG values as states in the controller, and compute the delta BG in the policy. Adding delta BG into the observation will increase the observation space, which might not always be a desired feature in general reinforcement learning algorithm development. I prefer to leave the flexibility to the users. Let me know what you think.

Jinyu
