### ISSUE TITLE
Does this simulator has the property of time-delay?

### ISSUE THREAD

**Issue by Tony-chenjw** [jxx123/simglucose#69]
I'm interested in whether this simulator is time-delayed or not? In the provided gym environment, if the patient was injected with certain amount of insulin, would this affect the patient's subcutaneous glucose (or obs) in the following few env steps, other than just next step?

**Comment by jxx123** [comment]
Yes, it is time-delayed. The dynamics are defined here https://github.com/jxx123/simglucose/blob/master/simglucose/patient/t1dpatient.py#L119-L208 The ODE follows the UVa/Padova Simulator, which models the insulin delay effect.
