### ISSUE TITLE
insulin unit and basal dosage

### ISSUE THREAD

**Issue by indrakur** [jxx123/simglucose#7]
I wonder about insulin unit used in this simulator.

Other thing is basal dosage in basal-bolus controller. The calculation is:
basal = u2ss * BW / 6000
What is the standard used in this controller? Also I can not find out what is u2ss. It is better if there is explanation about variables.

Thank you.

**Comment by jxx123** [comment]
The basal I use (basal = u2ss * BW / 6000) is under unit "U/min", where 1 U/min = 6000 pmol/L. "u2ss" is the steady state insulin rate per kilogram, and its unit is pmol/(L * kg).

Documentation is really an issue. I need to find time to address that. Thanks!

**Comment by EemeIi** [comment]
Hey @jxx123!

Further, in controller/basal_bolus_ctrller.py, line 56
`bolus = bolus / env_sample_time`
scales the bolus from "U/env_sample" to "U/min", right? Then, in simulation/env.py, there is
'insulin += tmp_insulin / self.sample_time'
again, so the stored output is divided by env_sample_time. The division from this line should be omitted, right?

**Comment by jxx123** [comment]
> Hey @jxx123!
> 
> Further, in controller/basal_bolus_ctrller.py, line 56:
> 
> `bolus = bolus / env_sample_time`
> 
> scales the bolus from "U/env_sample" to "U/min", right? Then, in simulation/env.py, there is
> 
> `insulin += tmp_insulin / self.sample_time`
> 
> again, so the stored output is divided by env_sample_time. The division from this line should be omitted, right?

Hi @EemeIi , the reason to divide bolus by env_sample_time is that the original bolus is the total amount (U), and the division is to convert it to rate (U/min).

For the line `insulin += tmp_insulin / self.sample_time`, the purpose is just to compute the average insulin rate in the sample time (see this [comment]( https://github.com/jxx123/simglucose/blob/44e7f350062fa9a602a4bbd2e3f5892deee1e44d/simglucose/simulation/env.py#L76)).  The reason for this is that the patient simulation sample time is 1 minute (see the [mini_step function](https://github.com/jxx123/simglucose/blob/44e7f350062fa9a602a4bbd2e3f5892deee1e44d/simglucose/simulation/env.py#L48)), but I would like to support arbitrary sample time in the simulator, hence I record the average values for all the variables including insulin.

**Comment by OneBirding** [comment]
Hello,  can you write down and upload the detailed documentation of the algorithm in your spare time?

**Comment by jxx123** [comment]
Hi I have added the documentation for the controller. I closed this issue for now, please feel free to reopen it if there is anything unclear. Thanks.

**Comment by KeAWang** [comment]
> 1 U/min = 6000 pmol/L
@jxx123 How can this be? The right hand side has no units of time. Should `u2ss` be instead pmol/L/min since it's a *rate*?

**Comment by zjp-zjp-zjp** [comment]
Hi, I'm wondering how u2ss is calculated? Or it's an independent parameter that needs to be input instead of calculated?

**Comment by goldenxingxing** [comment]
> > Hey [@jxx123](https://github.com/jxx123)!
> > Further, in controller/basal_bolus_ctrller.py, line 56:
> > `bolus = bolus / env_sample_time`
> > scales the bolus from "U/env_sample" to "U/min", right? Then, in simulation/env.py, there is
> > `insulin += tmp_insulin / self.sample_time`
> > again, so the stored output is divided by env_sample_time. The division from this line should be omitted, right?
> 
> Hi [@EemeIi](https://github.com/EemeIi) , the reason to divide bolus by env_sample_time is that the original bolus is the total amount (U), and the division is to convert it to rate (U/min).
> 
> For the line `insulin += tmp_insulin / self.sample_time`, the purpose is just to compute the average insulin rate in the sample time (see this [comment](https://github.com/jxx123/simglucose/blob/44e7f350062fa9a602a4bbd2e3f5892deee1e44d/simglucose/simulation/env.py#L76)). The reason for this is that the patient simulation sample time is 1 minute (see the [mini_step function](https://github.com/jxx123/simglucose/blob/44e7f350062fa9a602a4bbd2e3f5892deee1e44d/simglucose/simulation/env.py#L48)), but I would like to support arbitrary sample time in the simulator, hence I record the average values for all the variables including insulin.

I understand the moving average purposed behind the division. However, tmp_insulin is calculated in mini_step from U/min. I suppose this is dosage for one minute. Say self.sample_time is 5, and mini_step should give dosage for 5 minutes and then the moving average makes sense. I am still very confused and looking forward to your reply. Thank you very much.
