### ISSUE TITLE
Clarity on calculation of parameters apha and beta

### ISSUE THREAD

**Issue by edger-asiimwe** [jxx123/simglucose#75]
The empting rate, **_kempt(qsto)_**  of the liquid compartment of the stomach in this code is described below which I understand is **_kqut_** in this case.
```python
if Dbar > 0:
    aa = 5 / 2 / (1 - params.b) / Dbar
    cc = 5 / 2 / params.d / Dbar
    kgut = params.kmin + (params.kmax - params.kmin) / 2 * (
        np.tanh(aa * (qsto - params.b * Dbar)) -
        np.tanh(cc * (qsto - params.d * Dbar)) + 2)
else:
    kgut = params.kmax
```
In this [paper](https://ieeexplore.ieee.org/abstract/document/4015600?casa_token=TVP2UgpmlyIAAAAA:zkmVmjT8sBZ7ayef-YG5farqM4LdkSndXHzMK7sg88uACQBjykwLP2vPOr-Ar3PIZKv68H8JFI6w), A System Model of the Oral Glucose Absorption: Validation on Gold Standard Data shows that the parameters **alpha (aa)** and **beta (cc)** are as follows:
![image](https://github.com/jxx123/simglucose/assets/25789529/c640c26b-d7f7-4738-ba23-f51d687c8703)
Translating it to python would yield the code below
```python
aa = 5 / ( 2 * Dbar * (1 - params.b))
cc = 5 / (2 * Dbar * params.d)
```
I understand both yield the same result. For purposes of consistency and readability of the code with the equations in the  @[paper](https://ieeexplore.ieee.org/abstract/document/4015600?casa_token=TVP2UgpmlyIAAAAA:zkmVmjT8sBZ7ayef-YG5farqM4LdkSndXHzMK7sg88uACQBjykwLP2vPOr-Ar3PIZKv68H8JFI6w), do you think we can adopt the later option for this case?

@jxx123

**Comment by jxx123** [comment]
Sure, do you mind sending me a Pull Request? I can stamp it.

**Comment by edger-asiimwe** [comment]
I have updated the parameter **alpha** and **beta** via this [pull request](https://github.com/jxx123/simglucose/pull/76#issue-2189918678)

Thanks!
